### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by SanityZeroPercent** [matthew-soft/madeline#2]
this to do list is our target today.

- [x] add give tags commands
- [x] add orphan tags commands
- [x] fix delete tags commands
- [x] fix admin-delete tags commands

a.k.a. superseded #1
