### ISSUE TITLE
v3 To-Do

### ISSUE THREAD

**Issue by SanityZeroPercent** [matthew-soft/madeline#5]
# All Pull request are now go into `v3-dev` branch.

I have something that I might get the ideas from carl-bot and notsobot. i put it here just in case.

## carlbot

- [ ] Poll Systems (easy, but later on)
- [x] Some stats commands (about, guild join + guild left listener)
- [x] ckc commands

## notsobot

- [ ] OCR commands (kinda hard, might focusing at easier tasks)
